scrape_configs: 
  - job_name:       'node' 
    scrape_interval: 30s 
    static_configs: 
      - targets: ['node-exporter:9100'] 

  - job_name: 'cAdvisor' 
    scrape_interval: 30s 
    metrics_path: '/metrics' 
    static_configs: 
      - targets: ['cAdvisor:8050'] 