scrape_configs:
  - job_name:       'node'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s

    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          group: 'vm01server'

  #lets monitor containers        
  - job_name: 'cAdvisor'
    
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.105:8050']
        labels:
          group: 'containers'
  
  - job_name: 'sonarr'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.105:9707']
        labels:
          group: 'media'

  - job_name: 'radarr'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.105:9708']
        labels:
          group: 'media'

  - job_name: 'pihole'
    scrape_interval: 120s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.200.105:9617']
        labels:
          group: 'pihole'
